# Copyright (c) 2025-2026 Datalayer, Inc.
#
# BSD 3-Clause License

"""The Appspec reference, generated from its JSON Schema (LOOP S-07).

Every field, what it means in a sentence, its default, and an example taken
from the applications of the catalogue — so that the reference cannot drift
from what the spec accepts, nor show an example the spec would refuse.
``python -m agentspecs.apps`` writes it beside the schema.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

#: Where the page is kept in the documentation site, when the checkout has one.
REFERENCE_PATH = Path(__file__).resolve().parents[2] / "docs" / "docs" / "apps" / "reference.md"


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def type_of(prop: Mapping[str, Any]) -> str:
    """A field's type, in words a reader of the reference uses."""
    if "$ref" in prop:
        return f"[{_ref_name(prop['$ref'])}](#{_ref_name(prop['$ref']).lower()})"
    if "const" in prop:
        return f"`{prop['const']}`"
    if "enum" in prop:
        return " \\| ".join(f"`{value}`" for value in prop["enum"] if value != "")
    for key in ("anyOf", "oneOf"):
        if key in prop:
            kinds = [type_of(option) for option in prop[key] if option.get("type") != "null"]
            return " or ".join(kinds) or "null"
    kind = prop.get("type")
    if kind == "array":
        return f"list of {type_of(prop.get('items') or {})}"
    if kind == "object":
        extra = prop.get("additionalProperties")
        return f"mapping of {type_of(extra)}" if isinstance(extra, dict) else "mapping"
    return {"string": "text", "integer": "integer", "number": "number", "boolean": "true or false"}.get(
        str(kind), str(kind or "any")
    )


def _default(prop: Mapping[str, Any]) -> str:
    if "default" not in prop:
        return "—"
    value = prop["default"]
    if value in ("", [], {}, None):
        return "empty"
    return f"`{json.dumps(value, ensure_ascii=False)}`"


def _cell(text: str) -> str:
    return " ".join(str(text or "").split()).replace("|", "\\|")


#: For what no application of the catalogue sets, an example the spec accepts
#: (a test reads each one into an application of the catalogue).
EXTRA_EXAMPLES: Dict[str, Any] = {
    "team": "analyze-support-tickets:0.0.1",
    "model": "bedrock:us.anthropic.claude-sonnet-4-6",
    "skills": ["crawl:0.0.1"],
    "tools": ["current-time:0.0.1"],
    "permissions": {
        "spaces": [{"space": "support", "access": "read"}],
        "computer": {"browse": True},
    },
    "checks": {
        "guards": ["confidence-guard:0.0.1"],
        "gates": ["low-confidence-review"],
    },
    "avatar": "AstronautIcon",
    "banner": "SvgTutorialsHero",
}


def _catalogue_files() -> List[Path]:
    return sorted((Path(__file__).resolve().parent).glob("*.yaml"))


def examples() -> Dict[str, Any]:
    """For each top-level field, an example: as an application of the catalogue
    writes it — its file, not its dump, which leaves out what is at its
    default — and otherwise one of :data:`EXTRA_EXAMPLES`."""
    found: Dict[str, Any] = {}
    for path in _catalogue_files():
        document = yaml.safe_load(path.read_text()) or {}
        for key, value in document.items():
            found.setdefault(key, value)
    for key, value in EXTRA_EXAMPLES.items():
        found.setdefault(key, value)
    return found


def _table(properties: Mapping[str, Any], required: List[str]) -> List[str]:
    lines = ["| Field | Type | Meaning | Default |", "| --- | --- | --- | --- |"]
    for name, prop in properties.items():
        field = f"`{name}`" + (" (required)" if name in required else "")
        lines.append(
            f"| {field} | {_cell(type_of(prop))} | {_cell(prop.get('description', ''))} | {_cell(_default(prop))} |"
        )
    return lines


def reference_markdown(schema: Optional[Mapping[str, Any]] = None) -> str:
    """The reference page, as Markdown."""
    from agentspecs.apps import APP_SCHEMA, json_schema

    schema = schema or json_schema()
    definitions: Mapping[str, Any] = schema.get("$defs") or {}
    lines: List[str] = [
        "---",
        "sidebar_position: 2",
        "title: Appspec reference",
        "---",
        "",
        "<!-- Generated by `python -m agentspecs.apps` from the JSON Schema. Do not edit. -->",
        "",
        "# Appspec reference",
        "",
        f"Every field of an Appspec (`schema: {APP_SCHEMA}`), what it means, its default, and an example "
        "taken from an application of the catalogue. Nothing is written for a field at its default.",
        "",
        "## The application",
        "",
        *_table(schema.get("properties") or {}, list(schema.get("required") or [])),
        "",
        "## Examples",
        "",
        "Each from an application of the catalogue, as its file writes it.",
        "",
    ]
    for name, value in examples().items():
        lines += [f"### `{name}`", "", "```yaml", yaml.safe_dump({name: value}, sort_keys=False, allow_unicode=True).rstrip(), "```", ""]
    objects = {name: spec for name, spec in definitions.items() if spec.get("properties")}
    choices = {name: spec for name, spec in definitions.items() if "enum" in spec}
    if objects:
        lines += ["## Parts", ""]
        for name, spec in objects.items():
            lines += [f"### {name}", ""]
            if spec.get("description"):
                lines += [_cell(spec["description"]), ""]
            lines += [*_table(spec["properties"], list(spec.get("required") or [])), ""]
    if choices:
        lines += ["## Choices", "", "| Name | Values |", "| --- | --- |"]
        for name, spec in choices.items():
            values = ", ".join(f"`{value}`" for value in spec["enum"] if value != "")
            lines.append(f'| <a id="{name.lower()}"></a>{name} | {values} |')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
