# Copyright (c) 2025-2026 Datalayer, Inc.
#
# BSD 3-Clause License

"""The scene spec reference, generated from its JSON Schema (LOOP A-11).

Every field, what it means in a sentence, its default, and an example taken
from the scenes of the catalogue — the Appspec's reference, for scenes.
``python -m agentspecs.scenes`` writes it beside the schema.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

import yaml

from ..apps.reference import _cell, _table

#: Where the page is kept in the documentation site, when the checkout has one.
REFERENCE_PATH = Path(__file__).resolve().parents[2] / "docs" / "docs" / "scenes" / "reference.md"

#: For what no scene of the catalogue sets, an example the spec accepts (a
#: test reads each one into a scene of the catalogue).
EXTRA_EXAMPLES: Dict[str, Any] = {
    "entry": "sales",
}


def _catalogue_files() -> List[Path]:
    return sorted(Path(__file__).resolve().parent.glob("*.yaml"))


def examples() -> Dict[str, Any]:
    """For each top-level field, an example: as a scene of the catalogue writes it, else one of :data:`EXTRA_EXAMPLES`."""
    found: Dict[str, Any] = {}
    for path in _catalogue_files():
        document = yaml.safe_load(path.read_text()) or {}
        for key, value in document.items():
            found.setdefault(key, value)
    for key, value in EXTRA_EXAMPLES.items():
        found.setdefault(key, value)
    return found


def reference_markdown(schema: Optional[Mapping[str, Any]] = None) -> str:
    """The reference page, as Markdown."""
    from agentspecs.scenes import SCENE_SCHEMA, json_schema

    schema = schema or json_schema()
    definitions: Mapping[str, Any] = schema.get("$defs") or {}
    lines: List[str] = [
        "---",
        "sidebar_position: 2",
        "title: Scene spec reference",
        "---",
        "",
        "<!-- Generated by `python -m agentspecs.scenes` from the JSON Schema. Do not edit. -->",
        "",
        "# Scene spec reference",
        "",
        f"Every field of a scene spec (`schema: {SCENE_SCHEMA}`), what it means, its default, and an example "
        "taken from a scene of the catalogue. Nothing is written for a field at its default.",
        "",
        "## The scene",
        "",
        *_table(schema.get("properties") or {}, list(schema.get("required") or [])),
        "",
        "## Examples",
        "",
        "Each from a scene of the catalogue, as its file writes it.",
        "",
    ]
    for name, value in examples().items():
        lines += [
            f"### `{name}`",
            "",
            "```yaml",
            yaml.safe_dump({name: value}, sort_keys=False, allow_unicode=True).rstrip(),
            "```",
            "",
        ]
    objects = {name: spec for name, spec in definitions.items() if spec.get("properties")}
    choices = {name: spec for name, spec in definitions.items() if "enum" in spec}
    if objects:
        lines += ["## Parts", ""]
        for name, spec in objects.items():
            lines += [f"### {name}", ""]
            if spec.get("description"):
                lines += [_cell(spec["description"]), ""]
            lines += [*_table(spec["properties"], list(spec.get("required") or [])), ""]
    if choices:
        lines += ["## Choices", "", "| Name | Values |", "| --- | --- |"]
        for name, spec in choices.items():
            values = ", ".join(f"`{value}`" for value in spec["enum"] if value != "")
            lines.append(f'| <a id="{name.lower()}"></a>{name} | {values} |')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
