# Copyright (c) 2025-2026 Datalayer, Inc.
#
# BSD 3-Clause License

"""The catalog of visual components, as a page of the documentation (LOOP C-13, G-05).

Generated from the UI plugins (`ui-plugins/*.yaml`, `components`) so that the
page cannot list a component the catalogue does not have, nor miss one it has:
each plugin and the components it renders, and for Datalayer's own their
properties as a JSON Schema, their bindings, their events and an example.
``python -m agentspecs.ui_plugins`` writes it.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Dict, List

import yaml

#: The UI plugins of the catalogue.
PLUGINS_DIR = Path(__file__).resolve().parent / "ui-plugins"

#: Where the page is kept in the documentation site, when the checkout has one.
CATALOGUE_PATH = Path(__file__).resolve().parents[1] / "docs" / "docs" / "agents" / "ui-plugins" / "components.md"


def plugins() -> List[Dict[str, Any]]:
    """The UI plugins, as their files say, by id."""
    found = [yaml.safe_load(path.read_text()) or {} for path in sorted(PLUGINS_DIR.glob("*.yaml"))]
    return sorted(found, key=lambda plugin: str(plugin.get("id")))


def _cell(text: Any) -> str:
    """Text for a table cell, safe in MDX."""
    words = " ".join(str(text if text is not None else "").split())
    return words.replace("|", "\\|").replace("<", "&lt;").replace("{", "\\{").replace("}", "\\}")


def _type(prop: Mapping[str, Any]) -> str:
    if "enum" in prop:
        return " | ".join(f"`{value}`" for value in prop["enum"])
    kind = prop.get("type", "any")
    words = {"string": "text", "integer": "integer", "number": "number", "boolean": "true or false", "object": "mapping"}
    text = f"list of {_type(prop.get('items') or {})}" if kind == "array" else words.get(str(kind), str(kind))
    bounds = [f"{key} {prop[key]}" for key in ("minimum", "maximum", "minItems", "maxItems") if key in prop]
    return f"{text} ({', '.join(bounds)})" if bounds else text


def _default(prop: Mapping[str, Any]) -> str:
    if "default" not in prop:
        return "—"
    return f"`{json.dumps(prop['default'], ensure_ascii=False)}`"


def _names(values: List[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "nothing"


def _component(component: Mapping[str, Any]) -> List[str]:
    schema: Mapping[str, Any] = component.get("properties") or {}
    required = list(schema.get("required") or [])
    bindings: Mapping[str, Any] = component.get("bindings") or {}
    lines = [
        f"### `{component['id']}`",
        "",
        f"{component.get('emoji', '')} **{_cell(component['name'])}** · {_cell(component['category'])} — "
        f"{_cell(component['description'])}",
        "",
        "| Property | Type | Meaning | Default |",
        "| --- | --- | --- | --- |",
    ]
    for name, prop in (schema.get("properties") or {}).items():
        field = f"`{name}`" + (" (required)" if name in required else "")
        title = prop.get("title", "")
        meaning = f"**{_cell(title)}**. {_cell(prop.get('description', ''))}" if title else _cell(prop.get("description"))
        lines.append(f"| {field} | {_cell(_type(prop))} | {meaning} | {_cell(_default(prop))} |")
    lines += [
        "",
        f"- **Shows**: {_names(list(bindings.get('shows') or []))}.",
        f"- **Sends**: {_names(list(bindings.get('sends') or []))}.",
        f"- **Events**: {_names(list(component.get('events') or []))}.",
        "",
        "Its properties, as a JSON Schema:",
        "",
        "```json",
        json.dumps(schema, indent=2, ensure_ascii=False),
        "```",
        "",
    ]
    if component.get("example") is not None:
        lines += [
            "An example, valid against it:",
            "",
            "```yaml",
            yaml.safe_dump(component["example"], sort_keys=False, allow_unicode=True).rstrip(),
            "```",
            "",
        ]
    return lines


def catalogue_markdown() -> str:
    """The page of the catalog of visual components, as Markdown."""
    every = plugins()
    lines: List[str] = [
        "---",
        "sidebar_position: 2",
        "title: Components",
        "---",
        "",
        "<!-- Generated by `python -m agentspecs.ui_plugins` from ui-plugins/*.yaml. Do not edit. -->",
        "",
        "# The catalog of visual components",
        "",
        "Every visual component a UI plugin renders, by the name a surface gives it. "
        "A component no enabled plugin renders is not in the catalog: an Appspec that names one is refused "
        "(see [UI Plugins](./index.mdx)).",
        "",
        "| Plugin | Catalog | Enabled | Components |",
        "| --- | --- | --- | --- |",
    ]
    for plugin in every:
        count = len(plugin.get("components") or [])
        lines.append(
            f"| `{plugin['id']}` ({_cell(plugin['name'])}) | {_cell(plugin.get('catalog') or '—')} | "
            f"{'yes' if plugin.get('enabled') else 'no'} | {count or 'none of its own yet'} |"
        )
    lines.append("")
    for plugin in every:
        components = list(plugin.get("components") or [])
        if not components:
            continue
        standard = [c for c in components if c.get("standard")]
        own = [c for c in components if not c.get("standard")]
        lines += [
            f"## {_cell(plugin['name'])} (`{plugin['id']}`)",
            "",
            _cell(plugin.get("description")),
            "",
            f"Catalog `{plugin.get('catalog')}`: {len(standard)} standard components, whose properties are the "
            f"protocol's own ([{_cell(plugin['name'])}]({plugin['docs_url']})), and {len(own)} of Datalayer's own, "
            "whose properties are a JSON Schema the Canvas draws a properties form from.",
            "",
            "| Id | Name | Category | Standard | What it is for |",
            "| --- | --- | --- | --- | --- |",
        ]
        for component in components:
            anchor = f"[`{component['id']}`](#{component['id'].lower()})" if not component.get("standard") else f"`{component['id']}`"
            lines.append(
                f"| {anchor} | {component.get('emoji', '')} {_cell(component['name'])} | {_cell(component['category'])} | "
                f"{'yes' if component.get('standard') else 'no'} | {_cell(component['description'])} |"
            )
        lines.append("")
        if own:
            lines += [f"## {_cell(plugin['name'])}: Datalayer's own components", ""]
            for component in own:
                lines += _component(component)
    return "\n".join(lines).rstrip() + "\n"


if __name__ == "__main__":
    if CATALOGUE_PATH.parent.is_dir():
        CATALOGUE_PATH.write_text(catalogue_markdown())
        print(f"wrote {CATALOGUE_PATH}")
